---
title: "Cleaning US Census Data"
output: html_notebook
---

```{r message=FALSE, warning=FALSE, error=TRUE}
# load libraries
library(readr)
library(dplyr)
library(tidyr)
```

```{r message=FALSE, warning=FALSE, error=TRUE}
# load CSVs
files <- list.files(pattern = 'states_.*csv')
df_list <- lapply(files, read_csv)
us_census <- bind_rows(df_list)
```

```{r error=TRUE}
# inspect data
str(us_census)
head(us_census)

```

```{r error=TRUE}
# drop X1 column
us_census <- us_census %>% select(-X1)
head(us_census)

```

```{r error=TRUE}
# remove % from race columns and remove $ from Income column
us_census <- us_census %>%
  mutate(
    Hispanic = gsub('\\%','',Hispanic),
    White = gsub('\\%','',White),
    Black = gsub('\\%','',Black),
    Native = gsub('\\%','',Native),
    Asian = gsub('\\%','',Asian),
    Pacific = gsub('\\%','',Pacific),
    Income = gsub('\\$','',Income)) %>%
  mutate(
    Hispanic=round(as.numeric(Hispanic)/100, 4),
    White=round(as.numeric(White)/100, 4),
    Black=round(as.numeric(Black)/100, 4),
    Native=round(as.numeric(Native)/100, 4),
    Asian=round(as.numeric(Asian)/100, 4),
    Pacific=round(as.numeric(Pacific)/100, 4),
    Income=round(as.numeric(Income)/100, 4))
head(us_census)
```

```{r error=TRUE}
# separate GenderPop column
us_census <- us_census %>%
  separate(
    GenderPop, c('MalePop','FemalePop'), '_') %>%
  mutate(
    MalePop = gsub('M','',MalePop),
    FemalePop = gsub('F','',FemalePop))
head(us_census)
```

```{r error=TRUE}
# check for duplicate rows
us_census %>%
  duplicated() %>%
  table()
```

```{r error=TRUE}
# remove duplicate rows
us_census <- us_census %>% distinct()
head(us_census)
```
